import { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import { PortalProvider } from "./global-portal";
import { ReactNode } from "react";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={notoSansKR.className} suppressHydrationWarning={true}>
        <Layout>
          <PortalProvider>{children}</PortalProvider>
        </Layout>
      </body>
    </html>
  );
}

function Layout({ children }: { children: ReactNode }) {
  return <div className="my-0 mx-auto w-full max-w-[520px]">{children}</div>;
}
